name: Docker Image CI

on:
  push:
    branches: [ Zuki ]
  pull_request:
    branches: [ Zuki ]

jobs:

  build:

    runs-on: ubuntu-latest
    environment: test

    steps:
    - name: Check out code
      uses: actions/checkout@v2
      
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-southeast-1
        
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build, tag, and push image to Amazon ECR
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: sudahdigital
        IMAGE_TAG: latest
      run: |
        docker compose build
        docker tag sudahdigital:latest 374265332567.dkr.ecr.ap-southeast-1.amazonaws.com/sudahdigital:laravel
        docker tag php:8.0-fpm 374265332567.dkr.ecr.ap-southeast-1.amazonaws.com/sudahdigital:php
        docker tag composer:latest 374265332567.dkr.ecr.ap-southeast-1.amazonaws.com/sudahdigital:composer
        docker push 374265332567.dkr.ecr.ap-southeast-1.amazonaws.com/sudahdigital:laravel
        docker push 374265332567.dkr.ecr.ap-southeast-1.amazonaws.com/sudahdigital:php
        docker push 374265332567.dkr.ecr.ap-southeast-1.amazonaws.com/sudahdigital:composer
        
    - name: execute command
      run: |
         sshpass -p "${{secrets.SSH_PASSWORD}}" ssh -o StrictHostKeyChecking=no root@13.212.238.116 sh /opt/script/docker-pull.sh
