name: Docker Image CI

on:
  push:
    branches: [ Zuki ]
  pull_request:
    branches: [ Zuki ]

jobs:

  build:

    runs-on: ubuntu-latest
    environment: test

    steps:
    - name: Check out code
      uses: actions/checkout@v2
      
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-southeast-1
        
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build, tag, and push image to Amazon ECR
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: sudahdigital
        IMAGE_TAG: latest
      run: |
        docker compose build
        docker tag sudahdigital:latest $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
        docker tag composer:latest $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
        docker tag php:8.0-fpm $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
        docker tag nginx $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
        docker push $ECR_REGISTRY/sudahdigital:$IMAGE_TAG
        docker push $ECR_REGISTRY/composer:$IMAGE_TAG
        docker push $ECR_REGISTRY/php:$IMAGE_TAG
        docker push $ECR_REGISTRY/nginx:$IMAGE_TAG
